- typescript/web/src/components/dataset-class-list/class-item.tsx
- typescript/web/src/components/dataset-class-list/class-list.tsx
Before
After
Before
After
Before
After
> Better looking dnd

- typescript/web/src/worker/index.ts
So far, simply disabled precaching. 
We may want to investigate doing this asynchronously.
> Make Service Worker faster to install

- .github/workflows/ci.yml
- typescript/web/.gitignore
- typescript/web/bundlewatch.config.js
- typescript/web/next.config.js
- typescript/web/package.json
- typescript/web/sentry.client.config.js
- typescript/web/sentry.properties
- typescript/web/sentry.server.config.js
- typescript/web/src/pages/api/auth/[...nextauth].ts
- typescript/web/src/pages/api/graphql.ts
- typescript/web/src/pages/api/uploads/[...id].ts
- typescript/web/src/worker/index.ts
- typescript/web/src/worker/upload-server.ts
- yarn.lock
- Added Sentry integration to capture exceptions in the client, server and service worker
Exceptions are properly logged to Sentry. We tested to throw exceptions in every possible location (client, server and service worker) and all were properly caught:
The Sentry DSN needs to be added as an env variable named `NEXT_PUBLIC_SENTRY_DSN`
Closes #430
> Add Sentry to capture exceptions in client, server and service worker

- typescript/web/src/components/auth-manager/signin-button.tsx
- typescript/web/src/components/cookie-banner/cookie-banner.tsx
- typescript/web/src/components/export-button/export-button.tsx
- typescript/web/src/components/import-button/import-button.tsx
> Track more actions in GA

- typescript/common-resolvers/src/export/format-coco/coco-core/__tests__/converters.ts
- typescript/common-resolvers/src/export/format-coco/coco-core/converters.ts
- typescript/common-resolvers/src/export/format-yolo/export-to-yolo.ts
- typescript/web/src/components/export-button/export-modal/export-options-modal.tsx
- typescript/web/src/components/export-button/export-modal/formats.ts
- typescript/web/src/components/export-button/export-modal/index.tsx
- typescript/web/src/components/labelling-tool/openlayers-map/draw-bounding-box-and-polygon-interaction/create-label-effect.ts
- typescript/web/src/components/labelling-tool/options-tool-bar/delete-label-button.tsx
- Fixed a bug with images not having their referenced name with the "avoid name conflicts" option
- Ignored labels with undefined class
- Added a warning in the export modal in the case where there are some labels with an undefined class
> Updates on export feature

- typescript/web/src/components/export-button/export-modal/export-options-modal.tsx
- Avoid shrinking export button in export modal
Closes #473
> Avoid shrinking export button

- typescript/web/src/components/auth-manager/signin-modal/signin-modal.tsx
> Padding and logo size updated in sign-in modal

- typescript/web/src/components/labeling-tool/drawing-tool-bar/__stories__/iog-alert-dialog.tsx
- typescript/web/src/components/labeling-tool/drawing-tool-bar/drawing-tool.tsx
- typescript/web/src/components/labeling-tool/drawing-tool-bar/iog-alert-dialog.tsx
> Refactor auto polygon tool and workflow

- cypress/integration/online-access.ts
- typescript/web/src/components/workspace-switcher/workspace-menu/workspace-selection-popover/workspace-selection-popover.tsx
- Fix downshift ref errors in workspace switcher
Now we do not get the errors anymore in the console.
> Fix downshift ref errors in workspace switcher

- README.md
- Add information on env vars to readme
> Add information on env vars to readme

- cypress/integration/class-selection-popover.ts
- typescript/common-resolvers/package.json
- typescript/common-resolvers/src/utils/get-bounded-geometry-from-image.ts
- yarn.lock
- Change error thrown when user tries to create an invalid label
Closes #534
> Change error thrown when user tries to create an invalid label

- typescript/web/package.json
- yarn.lock
- Set `NEXTAUTH_URL` as production only in Vercel to fallback to `VERCEL_URL`
- Update next-auth to v4
Had to update `next-auth` from `v4-beta6` to `v4` to avoid the following error during build time:
Closes #552
> Enable to sign in with email in preview deployments

- typescript/web/src/components/website/banner/index.tsx
> Change banner

- .github/workflows/linkedin-orbit.yml
Import of history of linkedIn messages was removed too.
> Cron job to run once per day on the Linkedin to Orbit gitHub action

- typescript/web/src/components/website/Navbar/NavContent.tsx
- typescript/web/src/components/website/Navbar/NavLink.tsx
- typescript/web/src/components/website/Navbar/_data.tsx
Open jobs and documentation in new tabs
> Open links in other tabs in website

- typescript/web/src/components/datasets/delete-dataset-modal.tsx
> Images are not deleted in a deleted dataset

- typescript/common-resolvers/src/import/format-coco/index.ts
- typescript/common-resolvers/src/import/index.ts
- typescript/db/src/repository/upload-s3.ts
- typescript/web/src/pages/posts/[slug].tsx
- typescript/web/src/worker/upload-server.ts
> Fix dataset import

- strapi/config/database.js
- strapi/config/functions/bootstrap.js
- typescript/scripts/src/copy-supabase-bucket.ts
- typescript/web/src/components/website/Blog/BlogCard.tsx
- Made sure that Strapi won't recreate tables and populate data on each server launch
- Fix a problem with the clone bucker script
Strapi is right now using the prod DB on https://strapi.labelflow.ai/admin
> Have strapi running on prod DB

- typescript/web/src/components/members/table-actions.tsx
- typescript/web/src/components/members/table-content.tsx
- Edited workspace members list components to fully support dark mode.
Dark mode now works as expected in workspace members list.
This PR solves #633
> Dark mode for workspace members list

- data/__generated__/schema.graphql
- data/entities.graphql
- data/image.graphql
- typescript/common-resolvers/src/image.ts
- typescript/common-resolvers/src/types.ts
- typescript/db/migrations/20211222090111_add_metadata_field_in_image/migration.sql
- typescript/db/schema.prisma
- typescript/db/src/__generated__/schema.ts
- typescript/graphql-types/src/graphql-types.generated.ts
- typescript/web/src/connectors/apollo-client/__generated__/schema.ts
- typescript/web/src/worker/__generated__/schema.ts
> Add metadata field for image in schema and resolvers

- typescript/web/src/components/auth-manager/signin-modal/features.tsx
- typescript/web/src/components/members/new-member-modal.tsx
- typescript/web/src/components/members/table-actions.tsx
> Update some wordings for release

- typescript/db/package.json
- yarn.lock
> Update apollo-server version

- cypress/integration/golden-path.common.ts
- Skip the tutorial in the online golden path end to end test since this is a local feature
> Fix e2e tests flakiness

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
* Make issues faster to create by using comments for instructionis instead of plain text (so that we
don't have to remove them).
* Cleanup pull-request template
Up-to-date issues and pull-request templates
No
No
No
No
> Make issues faster to create and cleanup pull-request template

- typescript/web/src/components/dataset-classes/label-classes-table-row.tsx
- Set a proper background colour to dataset class list rows
#721
> Fixed dataset class list rows background

- typescript/web/src/pages/_app.tsx
- typescript/web/src/pages/_error.tsx
> Fix bug with being apparently signed out after error

- typescript/web/src/components/members/index.tsx
- typescript/web/src/components/members/table-actions.tsx
- typescript/web/src/pages/[workspaceSlug]/members/index.tsx
- Set a max width for the members list
- Update the local workspace alert
Due to the now limited width of the alert, the message is now displayed over 2 lines. @nicOwlas please review the updated UI 
Closes #725
> Update members list max width

- typescript/web/src/components/auth-manager/auth-manager.tsx
- typescript/web/src/components/auth-manager/index.ts
- typescript/web/src/components/auth-manager/signin-modal/__stories__/signin-modal.tsx
- typescript/web/src/components/auth-manager/signin-modal/divider-with-text.tsx
- typescript/web/src/components/auth-manager/signin-modal/email-signin.tsx
- typescript/web/src/components/auth-manager/signin-modal/index.ts
- typescript/web/src/components/auth-manager/signin-modal/oauth-signin.tsx
- typescript/web/src/components/auth-manager/signin-modal/signin-error.tsx
- typescript/web/src/components/auth-manager/signin-modal/signin-modal.context.tsx
- typescript/web/src/components/auth-manager/signin-modal/signin-modal.tsx
- typescript/web/src/pages/auth/signin.tsx
- Update the url sent by mail during a sign in
We can now sign in correctly even after an error in a previous attempt
Closes #731
> Fix wrong url sent during sign in

- typescript/web/src/components/welcome-manager/__stories__/welcome-modal.tsx
Welcome modal progress should not be shown anymore in Chromatic shapshots
No
No
Fixes #749 
No
> Correctly define parameters of the WelcomeWithoutCountDown story

- typescript/web/src/__stories__/hello.tsx
- typescript/web/src/components/website/Footer/Footer.tsx
- typescript/web/src/components/website/Footer/LinkGrid.tsx
- typescript/web/src/components/website/Footer/SubscribeForm.tsx
- Update footer for prevent overflow on mobile
Closes #701
> Switch /website footer layout orientation between horizontal on desktop and vertical on mobile

- typescript/web/src/components/website/Navbar/NavContent.tsx
I've changed the design of the GitHub link button of the /website NavBar.
This is the link version, please choose between #760 and #761 or close both.
https://github.com/labelflow/labelflow/issues/759#issuecomment-1008924997
No
Takes more space in the NavBar
Closes #759 
No
> Change website NavBar GitHub link design (link version)

- typescript/web/src/components/website/banner/index.tsx
> Update website banner with the new online workspaces and IOG features

- typescript/web/src/components/website/Navbar/NavContent.tsx
I've just changed `github` to `GitHub` in the `Star us on github` button (my bad 🙈).
GitHub is correctly spelled :octocat: 🎉 
No
No
No
No
> Correctly write the GitHub name in its star button

- typescript/web/next-sitemap.js
- Update sitemap config changing an env variable
Closes #789
> Make next-sitemap use a LABELFLOW_URL environment variable

- typescript/web/src/components/layout/top-bar/user-menu.tsx
- Fix random color gradient when using password less authentication
Closes #798
> Fix inverted ternary in user avatar for color selection

- README.md
> Fix typos in README and update our GitHub project URL

- typescript/web/src/components/import-button/__tests__/import-button.tsx
- typescript/web/src/components/import-button/import-button.fixtures.ts
- typescript/web/src/components/import-button/import-images-modal/__tests__/import-images-modal.tsx
- typescript/web/src/components/import-button/import-images-modal/modal-dropzone/import-dropped-files/import-images.ts
- typescript/web/src/components/import-button/import-images-modal/modal-dropzone/modal-dropzone.tsx
- typescript/web/src/utils/tests/data.fixtures.ts
- typescript/web/src/utils/upload-file.ts
- Fix tests on import button
- Fix tests on import images modal
> Fix tests on import modal

- .github/workflows/ci.yml
- typescript/web/src/components/export-button/export-modal/__stories__/export-format-card.tsx
- typescript/web/src/components/export-button/export-modal/__stories__/export-options-modal.tsx
- typescript/web/src/components/export-button/export-modal/__tests__/export-format-card.tsx
- typescript/web/src/components/export-button/export-modal/export-modal.context.tsx
- typescript/web/src/components/export-button/export-modal/modal-header.tsx
- Remove label without classes info from the export modal 
- Set black version in CI
closes #822
> Remove labels without classes info from the export modal

- typescript/web/package.json
- typescript/web/src/components/export-button/export-modal/__tests__/index.tsx
- typescript/web/src/components/export-button/export-modal/export-dataset.ts
- typescript/web/src/components/export-button/export-modal/export-modal.fixtures.ts
- typescript/web/src/components/export-button/export-modal/utils/__tests__/get-dataset-name.test.ts
- typescript/web/src/components/export-button/export-modal/utils/get-dataset-name.ts
- yarn.lock
> Fix export tests

- typescript/web/src/hooks/__tests__/use-images-navigation.tsx
- typescript/web/src/hooks/use-image-navigation.fixtures.ts
- typescript/web/src/hooks/use-images-navigation.query.ts
- typescript/web/src/hooks/use-images-navigation.ts
- Rework use-images-navigation hook tests
> Rework use-images-navigation hook tests

- typescript/web/src/components/graphiql/graphiql.tsx
- typescript/web/src/components/spinner/layout-spinner.tsx
- typescript/web/src/components/spinner/spinner.tsx
- typescript/web/src/pages/[workspaceSlug]/graphiql/index.tsx
- typescript/web/src/pages/graphiql.tsx
- Fix graphiql pages, centered spinners and dark mode spinners
Closes #862
> Fix graphiql pages, centered spinners and dark mode spinners

- typescript/web/src/components/datasets/dataset-list.tsx
I've updated the expiration date shown in MigrateLocalDatasetsModal
Date refers to tonight
No
Date could still change.
No but it contributes to #741 
No
> Update MigrateLocalDatasetsModal expiration date

- typescript/web/src/components/workspaces/workspaces.tsx
Updated the text for it to be more positive. It matches this mockup
> Update text on workspace list empty state

- .github/workflows/ci.yml
> Upload code-coverage in the test-typescript step

- typescript/common-resolvers/src/export/export-to-csv.ts
A small cleanup which was not blocking during merge of #894 
Code is cleaner
No
No
No
No
> Remove workspaceId and datasetId variables from export-to-csv s3 key extraction

- typescript/web/src/components/labeling-tool/openlayers-map/iog/click-and-hover.tsx
- Change query used to retrieve iog label infos
Closes #897
> Use correct query to retrieve iog label information

- typescript/common-resolvers/src/dataset.ts
- typescript/web/src/components/dataset-images-list/delete-image-modal.tsx
- typescript/web/src/components/dataset-images-list/images-list.tsx
- typescript/web/src/components/dataset-images-list/paginated-images-query.ts
- typescript/web/src/components/import-button/import-button.tsx
- typescript/web/src/components/import-button/import-images-modal/import-images-modal.tsx
- typescript/web/src/hooks/use-images-navigation.ts
- typescript/web/src/pages/[workspaceSlug]/datasets/[datasetSlug]/classes.tsx
- typescript/web/src/pages/[workspaceSlug]/datasets/[datasetSlug]/images/[imageId].tsx
- typescript/web/src/pages/[workspaceSlug]/datasets/[datasetSlug]/images/index.tsx
- typescript/web/src/pages/[workspaceSlug]/datasets/[datasetSlug]/index.tsx
- Update refetch queries when creating an image
- Query all images of a dataset when deleting an image to update navigation images
Closes #898
> Make thumbnails appear or disappear when adding or deleting images

- typescript/web/src/components/invitation-manager/index.stories.tsx
- typescript/web/src/components/invitation-manager/invitation-container.tsx
Some small cleanup for #874
Cleaner code
No
No
Code review on #874
No
> Cleanup InvitationContainer top-level layout

- typescript/web/src/pages/index.tsx
- typescript/web/src/pages/website.tsx
- typescript/web/src/utils/get-home-static-props.ts
- Use getStaticProps on home page instead of getServerSideProps to fetch preview articles
Closes #914
> Home page must be provided with preview articles

- typescript/web/src/components/auth/divider-with-text.tsx
- typescript/web/src/components/auth/oauth-sign-in.tsx
- typescript/web/src/components/auth/sign-in.tsx
- typescript/web/src/components/text-link.stories.tsx
- typescript/web/src/components/text-link.tsx
- typescript/web/src/pages/auth/signin.tsx
Update sign in page to use mobile design only
Closes #876
> Always use the mobile-like layout in sign-in page

- typescript/web/src/components/layout/top-bar/user-menu.tsx
> Switch the places of User and Preferences in MenuList (#857)

- typescript/web/src/components/website/banner/index.tsx
Website change date for the webinar on banner on website
> Set webinar date to March 24th on website banner

- cypress/integration/polygon-drawing.ts
- typescript/web/src/components/labeling-tool/drawing-tool-bar/drawing-tool.tsx
- typescript/web/src/components/labeling-tool/openlayers-map/draw-interaction/bounding-box-polygon.tsx
- typescript/web/src/components/labeling-tool/openlayers-map/draw-interaction/index.tsx
- typescript/web/src/components/labeling-tool/openlayers-map/openlayers-map.tsx
- typescript/web/src/components/labeling-tool/openlayers-map/select-and-modify-feature/select-interaction.tsx
- typescript/web/src/components/labeling-tool/options-tool-bar/edit-label-class-menu.tsx
- typescript/web/src/connectors/labeling-state/index.ts
- typescript/web/src/keymap.ts
- Add freehand drawing tool
Closes #639
> Add freehand drawing

- typescript/web/src/hooks/use-user.tsx
- Fix user not disconnected when not found in database
Closes #883
> Sign-out user when id is not found in database

- typescript/web/src/hooks/use-user.tsx
- typescript/web/src/pages/[workspaceSlug]/datasets/[datasetSlug]/index.tsx
- typescript/web/src/utils/index.ts
Redirect to 404 when workspace or dataset is not found
Closes #807
> Redirect to 404 when workspace or dataset is not found

- .github/workflows/ci.yml
- python/api/requirements.txt
- python/iog/dataloaders/helpers.py
- python/iog/networks/refinementnetwork.py
- python/iog/networks/sync_batchnorm/batchnorm.py
- python/iog/requirements.txt
Update black because of `click` incompatibility
More infos [here](https://github.com/psf/black/issues/2964)
> Update black version

- typescript/web/src/constants.ts
This is a follow-up of this bug https://github.com/labelflow/labelflow/pull/941#issuecomment-1079202137
URL should be correctly formatted now
No
No
No
No
> Remove trailing / from app and  documentation URL constants

- typescript/web/src/components/core/combo-box/combo-box.test.tsx
- typescript/web/src/components/core/search-input/search-input.test.tsx
- typescript/web/src/components/core/search-input/search-input.tsx
- typescript/web/src/components/labeling-tool/openlayers-map/select-and-modify-feature/index.tsx
- typescript/web/src/connectors/undo-store/create-undo-store.ts
- typescript/web/src/connectors/undo-store/effects/run-ai-assistant.effect.test.ts
- typescript/web/src/connectors/undo-store/effects/run-ai-assistant.effect.ts
- typescript/web/src/connectors/undo-store/effects/run-ai-assistant.test.ts
See #975 for details about the job done
More tests => less bugs
> Add some of the missing Ai Assistant tests
