typescript/web/src/components/website/Footer/LinkGrid.tsx
typescript/web/src/components/website/Navbar/NavLink.tsx
typescript/web/src/components/website/Navbar/_data.tsx

- Added a link to the documentation page in the website's nav bar and footer
Closes #419

Add link to documentation in website

---

typescript/web/src/components/labelling-tool/openlayers-map/edit-label-class.tsx
typescript/web/src/components/labelling-tool/options-tool-bar/edit-label-class-menu.tsx

- Fix bug in change class shortcut on azerty keyboards
- Fix bug in keys listener in edit label class menu that missing a dependency
This PR makes sure that when pressing a number on AZERTY keyboards (so actually pressing `SHIFT`+ `key`) the class is properly changed.
Instead of adding the two possibilities (class is changed both when pressing `SHIFT`+`key` or just `key`) I decided to implement only the change when pressing properly a number. Otherwise we would have allowed to change classes by pressing `SHIFT`+`key` on non-AZERTY keyboards, which causes interferences with other shortcuts in some keyboards.
For example in a spanish keyboard the slash is made with `SHIFT`+`7`, so when pressing that key we would not know if the user wants to set the class corresponding to shortcut 7 or if …

Fix bug in change class shortcut on azerty keyboards

---

typescript/web/src/components/labelling-tool/openlayers-map/openlayers-map.tsx
typescript/web/src/components/welcome-manager/welcome-modal.tsx
typescript/web/src/hooks/use-image-prefetching.ts

- Prefetch previous and next images when being in the labelling platform
- Fix a bug where the welcome modal would try to create the tutorial dataset even if the user already had one
The images are properly fetched (there is no loading spinner when navigating from one image to the next one even if the user never visited that image) but this did not solve the glitch problem of images navigation.
Closes #188

Prefetch previous and next images

---

typescript/common-resolvers/src/dataset.ts
typescript/web/src/components/datasets/__tests__/delete-dataset-modal.tsx
typescript/web/src/connectors/resolvers/__tests__/dataset.ts
typescript/web/src/pages/local/datasets/[datasetSlug]/classes/index.tsx
typescript/web/src/pages/local/datasets/[datasetSlug]/images/[imageId].tsx
typescript/web/src/pages/local/datasets/[datasetSlug]/images/index.tsx
typescript/web/src/pages/local/datasets/[datasetSlug]/index.tsx

- Fix bug of error being thrown when clearing site data and reloading page
Before when clearing site data on a page of type `[datasetSlug]/images/[imageId]` this error would be thrown:
Now with this PR the error is properly handled:

Fix bug of error being thrown when clearing site data and reloading page

---

data/__generated__/schema.graphql
data/queries.graphql
typescript/common-resolvers/src/dataset.ts
typescript/common-resolvers/src/image.ts
typescript/graphql-types/src/graphql-types.generated.ts
typescript/web/src/components/datasets/delete-dataset-modal.tsx
typescript/web/src/components/datasets/upsert-dataset-modal.tsx

- Add a query called `searchDataset` that allows to return `null` or `undefined` when querying a dataset that does not exist
- Call this query instead of the normal `dataset` query in `typescript/web/src/components/datasets/upsert-dataset-modal.tsx`
- Skip the `getDatasetByIdQuery` in `typescript/web/src/components/datasets/delete-dataset-modal.tsx` when `datasetId` is not defined to avoid throwing another error
No more errors are being thrown from the backend when creating a dataset
Closes #436

Fix bug of errors being thrown in service worker from create dataset modal

---

typescript/web/next.config.js

- Fix bug at build time when user does not have a Sentry token
In #460 the build of the web-app failed due to the Sentry token missing in the environment variables. This is needed for the Sentry CLI to upload the source maps to the relevant Sentry project, and it crashes if Sentry does not find the token to be able to connect to the relevant project.
Here we disable the source maps uploads if we can't find the Sentry token in the environment variables, enabling thus to compile the app. I tested to build the app removing the Sentry token env var and it worked, so this should fix #460.
Closes #460

Fix bug at build time when user does not have a Sentry token

---

typescript/web/src/components/export-button/export-modal/index.tsx

I moved the export template of the dataset from `dataset-${date}-${format}` to `${datasetSlug}-${format}-${date}`
This originated from the work on the webinar where I had to export different datasets and got lost between ambiguous names
For instance, I got: "dataset-2021-09-23T173448-coco" vs "dataset-2021-09-23T173832-coco"
With that change they become: "training-powerlines-coco-2021-09-23T173448" vs "test-powerlines-coco-2021-09-23T173832" which is much more readable

Disambiguate dataset name at export

---

typescript/web/src/components/meta.tsx
typescript/web/src/pages/_app.tsx
typescript/web/src/pages/posts/[slug].tsx

- Change metadata fields in the blog post page in order to display the post image and description in social media previews
The `<Meta />` tag that was placed in `_app.tsx` was overwriting the preview image set by the blog post page, so I added a `noImage` prop so that it does not get ovwerwritten.
Closes #470

Display blog post details in social media previews

---

cypress/integration/class-selection-popover.ts
cypress/integration/classification.ts
cypress/integration/dataset-manipulation.ts
cypress/integration/image-navigation.ts
typescript/web/src/components/labeling-tool/drawing-tool-bar/drawing-tool.tsx
typescript/web/src/components/labeling-tool/openlayers-map/edit-label-class.tsx

- Enable to set classification class from shortcut
- Reset selected label when changing the selected tool to any drawing tool
Closes #491

Enable to set classification class from shortcut

---

.github/workflows/ci.yml

- Replaced the value for `POSTGRES_EXTERNAL_URL` in the tests action of the CI by a hardcoded value pointing to the DB in the container

Replace usage of external url env var by hardcoded url for tests

---

typescript/web/src/components/import-button/import-images-modal/import-progress.tsx

- Change loading indicator tooltip when uploading files
Closes #577

Change loading indicator tooltip when uploading files

---

typescript/db/src/resolvers/invite-member.ts
typescript/web/src/pages/api/email/send-invitation.ts

- The inviteUser resolver now forwards the origin header to the API route `email/send-invitation`.
- The API route `email/send-invitation` now use the origin from the header if it is available.
Now, **invite emails** will correctly direct you to the URL origin that triggered the invite (even on dev branches).
This partially solves the original issue. At least, **it should never happen in production** as the URL origin doesn't change.
However, **this doesn't fix the magic link** ... It still uses the VERCEL_URL env var. And this one is provided by Vercel and changes at every commit. Vercel doesn't provide an env var for the related preview URL (which is shared across all the deployments of a PR)...
If for a particular reason, you want to use the preview URL, you can copy the end of the …

fix user invitation urls

---

typescript/web/src/pages/api/graphql.ts

- Increased the `bodyParser` size limit of the Graphql API route as per the [Vercel docs](https://nextjs.org/docs/api-routes/api-middlewares#custom-config)
Closes #609

Increase IOG size limit

---

typescript/web/src/components/meta.tsx
typescript/web/src/constants.ts
typescript/web/src/pages/posts/[slug].tsx

Fixed image preview on Facebook. 
The fix on https://github.com/labelflow/labelflow/pull/616 was only working for Vercel preview deployments, it wasn't working on prod.
To fix this, I had to specify a correct value for `og:url`. 
By default, it was always pointing to `labelflow.ai`, from what I've read (I'm not the most experienced on this part) it has o point toward the URL of the article itself.
I also added a few meta tags specific to articles on the `/posts/[slug]` url.
Now I hope it works as expected, it should, but to make sure this is working, we have to deploy it on labelflow.ai
The behaviour was different between branch deployments and prod because we put a default `og:url` value to `labelflow.ai`, as explained on Facebook documentation …

Set correct value for `og:url` of articles

---

typescript/web/src/components/datasets/dataset-card-box.tsx
typescript/web/src/components/datasets/dataset-card.tsx
typescript/web/src/components/datasets/index.ts
typescript/web/src/components/datasets/new-dataset-card.tsx
typescript/web/src/components/layout/tab-bar/tab-bar.tsx
typescript/web/src/pages/[workspaceSlug]/datasets/index.tsx

- Add a spinner when the datasets are loading
- Add a reusable component wrapping the `NewDatasetCard`, the `DatasetCard` and the `LoadingCard` components
- Fix key error in tab bar
A spinner will be displayed when the datasets are loading
We can now use the `DatasetCardBox` component to obtain a flexible `Box` having the same size as the other "Cards". Modifying the `DatasetCardBox` component will update all 3 components quoted before
This PR will solve #627
This PR will close #653

Add spinner on loading datasets and add reusable card box component

---

typescript/common-resolvers/src/import/format-coco/__tests__/__snapshots__/converters.ts.snap
typescript/common-resolvers/src/import/format-coco/__tests__/converters.ts
typescript/common-resolvers/src/import/format-coco/converters.ts
typescript/common-resolvers/src/import/format-coco/index.ts
typescript/common-resolvers/src/utils/__tests__/validate-upload-mime-types.ts
typescript/common-resolvers/src/utils/validate-upload-mime-types.ts
typescript/web/src/components/import-button/import-images-modal/modal-dropzone/dropzone.tsx

- Images in imported zip files for COCO do not need to be in the "images" subfolder anymore, but can be anyway in the archive structure.
- IDs of entities in COCO are not expected anymore to following a specific pattern (starting from 1, without gaps, ...)
- Annotations from COCO that have no segmentation will be considered and imported as box labels, according to their bbox data.
- Put a common source of authority for files mime types support for both front-end components and back-end importers in `typescript/common-resolvers/src/utils/validate-upload-mime-types.ts`
Images are just looked into the zip files from their extension, the best practice would be to also look into their binary data for proper markers of their mime type, but we need to do it in a way that is both supported by …

COCO import bug fixes and improvements

---

typescript/web/src/components/class-selection-popover/class-selection-popover.tsx

Fixed warning:
```text
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `ClassSelectionPopover`. See https://reactjs.org/link/warning-keys for more information.
at Styled(div) (/Users/bbenoist/src/labelflow/workspaces/node_modules/@emotion/react/dist/emotion-element-deca0de5.cjs.dev.js:35:23)
at ClassSelectionPopover (/Users/bbenoist/src/labelflow/workspaces/typescript/web/src/components/class-selection-popover/class-selection-popover.tsx:74:3)
at div
at /Users/bbenoist/src/labelflow/workspaces/typescript/web/src/components/labeling-tool/openlayers-map/edit-label-class.tsx:81:6
at ApolloProvider (/Users/bbenoist/src/labelflow/workspaces/node_modules/@apollo/client/react/context/ApolloProvider.js:5:21)
at wrapper …
```

Define a unique key prop in class-selection-popover list

---

typescript/common-resolvers/src/utils/validate-workspace-name.ts
typescript/db/package.json
typescript/db/src/repository/workspace.ts
typescript/react-openlayers-fiber/package.json
typescript/utils/package.json
typescript/utils/src/__tests__/override-error.test.ts
typescript/utils/src/index.ts
typescript/utils/src/override-error.ts
typescript/web/src/components/settings/workspace/profile.tsx
typescript/web/src/components/toast.ts
typescript/web/src/components/workspace-name-input/workspace-name-input.context.tsx
typescript/web/src/components/workspace-name-input/workspace-name-input.fixtures.tsx
typescript/web/src/components/workspace-switcher/create-workspace-modal/create-workspace-modal.tsx
typescript/web/src/components/workspace-switcher/create-workspace-modal/create-workspace.mutation.ts
typescript/web/src/utils/get-apollo-error-message.tsx
yarn.lock

I've added `getApolloErrorMessage` which tries to find the more meaningful error as possible so that it can be displayed to the user.
* Prisma errors are not fully typed
* Apollo errors are not fully typed
We might miss additional errors.
Closing #710 
Also related with #712 
No

Display a more meaningful error message in the app when createWorkspace fails

---

typescript/web/src/components/dataset-classes/upsert-class-modal/create-label-class.mutation.ts
typescript/web/src/components/dataset-classes/upsert-class-modal/modal-body.tsx
typescript/web/src/components/dataset-classes/upsert-class-modal/modal-context.tsx
typescript/web/src/components/dataset-classes/upsert-class-modal/modal-footer.tsx
typescript/web/src/components/dataset-classes/upsert-class-modal/update-label-class-name.mutation.ts
typescript/web/src/components/dataset-classes/upsert-class-modal/upsert-class-modal.tsx

- Prevented class creation modal form from being submitted again while a query to create a new class is still ongoing.
- It shouldn't be possible anymore to create multiple classes with the same name at once
Solves #705

Fix bug creating duplicate label classes from modal

---

typescript/react-openlayers-fiber/src/__stories__/accessible.stories.tsx
typescript/react-openlayers-fiber/src/__stories__/basic.stories.tsx
typescript/react-openlayers-fiber/src/__stories__/draw-and-modify-features.stories.tsx
typescript/react-openlayers-fiber/src/__stories__/draw-shapes.stories.tsx
typescript/react-openlayers-fiber/src/__stories__/popup.stories.tsx
typescript/react-openlayers-fiber/src/__stories__/turf.stories.tsx
typescript/react-openlayers-fiber/src/__stories__/wms-tiled.stories.tsx
typescript/react-openlayers-fiber/src/__stories__/xyz.stories.tsx
typescript/web/src/components/welcome-manager/__stories__/welcome-modal.tsx
typescript/web/src/components/welcome-manager/steps/welcome.tsx
typescript/web/src/components/welcome-manager/welcome-modal.tsx
typescript/web/src/components/workspace-name-input/workspace-name-input.fixtures.tsx
typescript/web/src/components/workspace-name-input/workspace-name-message.tsx
typescript/web/src/components/workspace-switcher/create-workspace-modal/__stories__/create-workspace-modal.stories.tsx
typescript/web/src/components/workspace-switcher/create-workspace-modal/__tests__/create-workspace-modal.test.tsx
typescript/web/src/pages/_app.tsx
typescript/web/src/utils/mockable-location.tsx

- Simply disabled snapshot testing for the non-deterministic stories of react-openlayers-fiber
- Disabled the snapshot test for the WelcomeModal with the countdown
- Added a new story of the WelcomeModal without a countdown. Added snapshot tests for this story
- Make WorkspaceCreationModal and WorkspaceNameInput components accept an `origin` prop only specified on stories.
To be accepted only once: 
https://www.chromatic.com/build?appId=60a646559841590039471afc&number=2644
I am not sure to understand why, but it seems that the UI validation step thought I added new stories:
https://www.chromatic.com/build?appId=60a646559841590039471afc&number=2644

Disable non-deterministic react-openlayers-fiber stories

---

typescript/web/src/components/members/new-member-modal.tsx
typescript/web/src/utils/validate-email.tsx

trim white spaces around email addresses
An email address can now have leading or trailing white spaces around it and still be valid as it is trimmed prior to verification.

Trim white spaces around email addresses

---

package.json
setup-tests.ts
yarn.lock

I've increased the default timeout used with testing-library `waitFor` function.
CI tests should not fail randomly anymore 🚀 
Our tests are too slow to execute, even when only testing a single file.
We'll have to wait more time when tests timeouts are legit 🐌
Might fix #730 🙏 
**TODO** Create issue `Make our unit tests run faster`

Increase testing-library/react default timeout to 30s

---

typescript/db/migrations/20220105162621_optimized_indexes/migration.sql
typescript/db/schema.prisma

WIP
So far, I've just added a few indexes for:
- The most obvious filters use-cases
- createdAt order by
It would be nice to investigate a bit the efficiency of those indexes before continuing. Here is a non-exhausting list of subjects to investigate:
- Do we need created at for order by
- Do we need to add compound indexes for order by and filters (i.e. `createdAt, datasetId`) And in which order should we write it.
- Check existing order of compound indexes

Add and optimize DB schema indexes

---

cypress/integration/invitation-manager.online.ts
typescript/db/src/resolvers/__tests__/dataset.ts
typescript/web/src/components/labeling-tool/openlayers-map/__tests__/edit-label-class.tsx

Some tests were skipped.
```text
Test Suites: 69 passed, 69 total
Tests:       504 passed, 504 total
Snapshots:   6 passed, 6 total
Time:        129.025 s, estimated 173 s
```
I still don't really understand why these tests were skipped.
* It wasn't clear why they were some `it.only`
* I'm sure that we can resolve most the flacky issues.
Flacky tests will be back
No more skipped tests

Don't skip any Jest test

---

typescript/web/.gitignore
typescript/web/next-env.d.ts
typescript/web/package.json
yarn.lock

- Upgrade next version to 12.0.7
As `next` is generating `next-env.d.ts` on every build, a line has disappeared from ours, probably due to a change from `next`. We could add this file in our `.gitignore` if we want to avoid seeing this file move again in the future.

Update next to version 12.0.7

---

cypress.json

I've increased the Cypress default timeout to 60 seconds so that we can see if it reduces the amount of random e2e test failures.
e2e tests will fail after 1mn instead of 30s
No
It'll be slower to know that we did something wrong.
Might resolve #730 
#742 (already opened during #740 )

Increase default Cypress timeout to 60s

---

typescript/web/src/components/auth-manager/signin-modal/__stories__/signin-modal.tsx
typescript/web/src/components/auth-manager/signin-modal/email-signin.tsx
typescript/web/src/components/auth-manager/signin-modal/signin-error.tsx
typescript/web/src/components/auth-manager/signin-modal/signin-modal.context.tsx

- Update the error message when a user try to sign in with a different method than the first he choose
- Add a trim function for the error message as Google seems to add a `#` when redirecting from its login page
It seems that when you first use the Google login, when it redirects you to labelflow page, it adds a `#` at the end of URL which cause the error message to be incorrectly displayed (it showed the `default` one as it didn't match any other)
Closes #708

Update error message when different signin method is used

---

typescript/common-resolvers/src/dataset.ts
typescript/common-resolvers/src/label.ts
typescript/common-resolvers/src/utils/add-typename.ts
typescript/common-resolvers/src/utils/index.ts
typescript/db/src/resolvers/workspace.ts
typescript/web/src/connectors/resolvers/workspace.ts

- Made the `datasets` queries within a workspace to properly propagate their type, so that aggregate queries can properly know for which parent they are aggregating.

Fix bad aggregates count for workspace > datasets queries

---

typescript/web/src/components/auth-manager/signin-button.tsx
typescript/web/src/components/auth-manager/signin-modal/signin-modal.context.tsx
typescript/web/src/components/import-button/import-button.tsx
typescript/web/src/components/layout/top-bar/user-menu.tsx
typescript/web/src/components/settings/workspace/billing.tsx

I have:
* Added a `trackEvent` named `signin_${method}` which is called when we click on one of the `Sign in` buttons of the `SignInModal`
* Added a `trackEvent` named `manage_billing` which is called when we click on the `Manage billing` button of the workspace settings page.
* Factorized ImportButton and UserMenu while I was looking for existing events
The `signin_${method}` and `manage_billing` events should appear in the analytics
* I had to match with the existing names (e.g. `signin` instead of `sign-in`).
* Some code is duplicated
No
Closes #733 
No

Track click on a sign-in method and on manage billing

---

typescript/web/src/components/dataset-classes/upsert-class-modal/create-label-class.mutation.ts

In `create-label-class.mutation.ts` the `CREATE_WORKSPACE_MUTATION` was given as argument to the `useMutaion` used to create datasets. Hopefully `CREATE_DATASET_MUTATION` was given as argument to the call of the function generated by `useMutation` which prevented the code from having very weird errors.
Thanks @Jordanlelay for spotting the issue!
It does not really fixes a bug as explained above but at least now the dependency-chain is correct.
I've pushed by mistake on `main` since the `Include administrators` protection rule had been unchecked. This is now fixed.
No
No
No

Configure the createLabelClass mutation when calling useMutation

---

typescript/web/src/components/layout/top-bar/user-menu.tsx
typescript/web/src/components/settings/workspace/danger-zone/delete-workspace.mutation.ts
typescript/web/src/components/workspace-switcher/workspace-switcher.tsx
typescript/web/src/pages/[workspaceSlug]/index.tsx
typescript/web/src/pages/index.tsx

- Remove lastVisitedWorkspace cookie
- Remove Local workspace from switcher
Closes #773
Closes #774

Don't redirect to lastVisitedWorkspaceSlug anymore and remove local workspace from the switcher

---

typescript/common-resolvers/src/export/index.ts
typescript/web/src/components/export-button/export-modal/export-dataset.ts

- Fix exports from workspace datasets using the wrong URL (used the upload URL instead of the download URL).
- Fix downloaded files of exports having no extension. 
Exports from workspace datasets should now produce properly downloadable files.
Fixes #751

Fix exports not working from datasets in workspaces

---

typescript/web/src/components/pagination/pagination-footer.tsx

- Fix bug on datasets pagination
Add a left directive on pagination to override potential padding inherited from parent

Make pagination footer ignore its parent padding

---

typescript/common-resolvers/src/utils/__tests__/thumbnail-url.ts
typescript/common-resolvers/src/utils/thumbnail-url.ts
typescript/db/package.json
typescript/db/src/repository/image-processing.ts
typescript/web/src/components/import-button/import-images-modal/constants.ts
yarn.lock

- Update image batch size and amount for avoiding timeouts when uploading: was 2 batches of 10, now is 20 batches of 2.
- Enhance thumbnail generation performance using parallelisation and generating smaller thumbnail sizes on the largest one, instead of the original image.
We can now upload several images without experiencing timeouts
There is a limitation on the size of the image we can upload. I tried to upload the image `LargeImageTest.png` from our `very large images` dataset which is 23.6 Mo and it fails rather quickly with an `Array buffer allocation failed` error. 
It most likely comes from the serverless function that runs out of memory, probably when Jimp try to read the image.
The image is at a resolution of 8000x10000 (80M pixels) which should be handled by our …

Improve image upload performance

---

typescript/web/src/components/website/Navbar/NavContent.tsx

I've changed the look of the "Star us on GitHub" button on the website so that it matches the shape of the "Try it now" button when hovered
The GitHub button now fits better with the "Try it now button" when hovered
No
https://github.com/labelflow/labelflow/issues/759#issuecomment-1008924997
No
No

In website, use ghost variant on the GitHub button

---

.github/workflows/ci.yml
.storybook/main.js

I've listed the storybook directories and only included the ones which were not causing the Storybook build to fail.
Storybook should work again.
Storybook does not print which story is causing the build to fail.
* Each `__stories__` directory is explicitly listed in the `.storybook/main.js` file.
* We'll have to revert the changes once the stories gets fixed.
No but it contributes to #848 
> **TODO**: Add task "Revert d320ec6855c2cfc5fd784f859e96ff4b02ed62a1" at the end of #646

Only build the working Storybook files until the service worker is fully dropped

---

.github/workflows/ci.yml
jest.config.ts

- Change Jest tests config to generate an lcov coverage report
- Add a CI action to publish lcov data to CodeClimate

Add Jest tests coverage to CodeClimate

---

typescript/common-resolvers/src/export/format-coco/add-image-dimensions-to-labels.ts
typescript/common-resolvers/src/export/format-coco/coco-core/__tests__/converters.ts
typescript/common-resolvers/src/export/format-coco/coco-core/converters.ts
typescript/common-resolvers/src/export/format-coco/coco-core/types.ts
typescript/common-resolvers/src/export/format-coco/export-to-coco.ts
typescript/common-resolvers/src/export/format-yolo/export-to-yolo.ts

- Rework the way labels are exported
- Remove unused flickr_url
The labels, labelClasses and images of a dataset are now queried once for all at the beginning of the export procedure. A temporary object is built for fast access when iterating over the labels / images.
Tests I've conducted over a 11000+ labels dataset:
- yolo export -> From ~20s to ~10s
- coco export -> From `timeout` to ~8s
The tests were **only** focusing on labels and not images. If too much timeouts because of images happen, there is another way we could potentially improve performances:
- In both COCO and YOLO exports, for each image, this query is executed: `await repository.upload.get(image.url, req);`, returning an `ArrayBuffer` of the to-be-exported image. We could potentially batch these calls as we already have …

Fix timeout on label export

---

typescript/web/src/components/workspace-switcher/create-workspace-modal/create-workspace.mutation.ts

On workspace creation, make the mutation await the `refetchQueries` before changing its status to be complete.
No more errors after workspace creation.
#877

Fix workspace not found error after creation

---

typescript/web/src/hooks/use-image-navigation.fixtures.ts
typescript/web/src/hooks/use-images-navigation.test.tsx
typescript/web/src/pages/auth/signin.tsx

CI tests are sometimes failing because of a supposed race-condition in use-images-navigation test for values while loading.
I've increased the query response delay so that we can hope that the expectations will be tested before the query has ended-up being executed.
Test should not be flacky anymore
I can't reproduce the issue on my machine
There is a 100ms forced delay in the corresponding tests
No
No

Add extra delay in the loading state tests of useImagesNavigation

---

typescript/web/src/components/logo/nav-logo.tsx
typescript/web/src/components/workspaces/local-workspace-fallback.tsx

I've changed the LocalWorkspaceFallback component code so that it redirects to `/workspaces` when a user is authenticated and has at-least 1 workspace.
Users should not be automatically redirected to `lastWorkspaceId`
Code needed a bit of factorization so I've used a context to ensure a "purely-functional" state.
Until we have a real homepage, we'll have to use this hacky behavior.
Not created (was mentioned during the DSM)
* Change the URLs and simplify the code (remove context) once we have a real homepage (or remove this whole `/local` fallback if month have passed since)

Make the /local fallback page redirect to /workspaces when appropriate

---

.github/workflows/ci.yml

I've removed the auto-release from GitHub CI as it was failing and because it could trigger unwanted revision bumps.
This way the whole CI would pass on main.
Releases and tags can't be created anymore (they already weren't for months actually)
No
No
No
We should think about how tell which kind of version bump should occur once we write our commits. They are tools for this but it needs investigation.

Remove buggy auto-release

---

data/__generated__/schema.graphql
data/import.graphql
typescript/common-resolvers/src/import/format-coco/index.ts
typescript/common-resolvers/src/import/index.ts
typescript/common-resolvers/src/import/types.ts
typescript/db/src/__generated__/schema.ts
typescript/graphql-types/src/graphql-types.generated.ts
typescript/web/src/components/import-button/import-images-modal/import-images-modal.test.tsx
typescript/web/src/components/import-button/import-images-modal/import-progress.tsx
typescript/web/src/components/import-button/import-images-modal/modal-dropzone/file-statuses.tsx
typescript/web/src/components/import-button/import-images-modal/modal-dropzone/import-dropped-files/import-datasets.tsx
typescript/web/src/components/import-button/import-images-modal/modal-dropzone/import-dropped-files/import-images.ts
typescript/web/src/components/import-button/import-images-modal/modal-dropzone/import-dropped-files/index.tsx
typescript/web/src/components/import-button/import-images-modal/modal-dropzone/modal-dropzone.tsx
typescript/web/src/components/import-button/import-images-modal/modal-url-list/import-urls.tsx
typescript/web/src/components/import-button/import-images-modal/modal-url-list/modal-url-list.tsx
typescript/web/src/components/import-button/import-images-modal/modal-url-list/url-statuses.tsx
typescript/web/src/components/import-button/import-images-modal/types.ts

- Prevented COCO import from trowing an error when encountering crowd/RLE annotations, skipping them instead.
- On import modal:
- Added a message with the number of ignored crowd/RLE annotations if there are any.
- Changed the icon for JSON files and ZIP files.
#860

Fix coco import fail when containing crowd RLE annotations

---

typescript/react-openlayers-fiber/src/__stories__/basic.stories.tsx
typescript/react-openlayers-fiber/src/__stories__/bing.stories.tsx

I've just disabled the Bing story from Chromatic snapshots
We miss the (spammy) Chromatic review but it's not that useful for this component anyway.
No
No
No

Ignore the constantly-changing Bing story from react-openlayers-fiber Chromatic reports

---

typescript/web/package.json
typescript/web/src/connectors/labeling-state/index.ts
yarn.lock

Following my PR on upstream repo ( https://github.com/Diablow/zustand-store-addons/pull/6 ), I'm now propagating the changes on our codebase.
No more `// ts-ignore` in `typescript/web/src/connectors/labeling-state/index.ts`.
No
No
No but it confirms that https://github.com/Diablow/zustand-store-addons/issues/2 is fixed
No

Update zustand-store-addons to version 0.1.12

---

typescript/web/src/components/import-button/import-images-modal/import-images-modal.stories.tsx
typescript/web/src/components/import-button/import-images-modal/modal-dropzone/file-statuses.stories.tsx
typescript/web/src/components/import-button/import-images-modal/modal-dropzone/file-statuses.tsx

I've rolled-back out the color of the alternate row representing a file import status which was broken:
Color should be OK now
No
No
No

Use correct color in alternate import file status row

---

typescript/db/migrations/20220404081825_label_ai_assistant_id/migration.sql
typescript/db/schema.prisma
typescript/db/src/resolvers/ai-assistant.resolver.ts

I've added the AI Assistant ID in the `Label` entity of the DB schema.
We can now acknowledge that a label has been created with an AiAssistant.
DB relations are not complete as we don't store AI Assistant in it yet.
_No issue opened for it AFAIK but it's related with #958_
No

Store AiAssistant ID in db when creating new labels

---

typescript/web/src/components/toast.ts

I've reduced the default successful toast duration to 5s
Toast should take less time to disappear
No
No
No
No

Set useSuccessToast default duration to 5s
